name: bert_uncased_L_12_H_768_A_12
dir: "modules/text/semantic_model/bert_uncased_L_12_H_768_A_12"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/bert_uncased_L_12_H_768_A_12/assets.tar.gz
    dest: assets
    uncompress: True
