name: chinese-electra-base
dir: "modules/text/semantic_model/chinese_electra_base"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/chinese_electra_base/assets.tar.gz
    dest: assets
    uncompress: True
