name: human_pose_estimation_resnet50_mpii
dir: "modules/image/semantic_segmentation/deeplabv3p_xception65_humanseg/"
exclude:
    - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/hub_dev/deeplabv3p_xception65_humanseg_model.tar.gz
    dest: .
    uncompress: True
