name: ernie_v2_eng_base
dir: "modules/text/semantic_model/ernie_v2_eng_base"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie_v2_eng_base/assets.tar.gz
    dest: assets
    uncompress: True
