name: ernie_v2_eng_large
dir: "modules/text/semantic_model/ernie_v2_eng_large"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie_v2_eng_large/assets.tar.gz
    dest: assets
    uncompress: True
