name: mobilenet_v2_animals
dir: "modules/image/classification/mobilenet_v2_animals"
exclude:
  - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/cv/mobilenet_v2_animals.tar.gz
    dest: model
    uncompress: True
