name: porn_detection_gru
dir: "modules/text/text_review/porn_detection_gru"
exclude:
  - README.md
  - test.py
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/porn_detection_gru_infer_model.tar.gz
    dest: .
    uncompress: True
