name: pyramidbox_lite_server_mask
dir: "modules/image/face_detection/pyramidbox_lite_server_mask"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/paddle_model/pyramidbox_lite_server_mask_detectoion.tar.gz
    dest: .
    uncompress: True
