name: pyramidbox_lite_mobile_mask
dir: "modules/image/face_detection/pyramidbox_lite_mobile_mask"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/paddle_model/face_detector_mask.tar.gz
    dest: .
    uncompress: True
