name: pyramidbox_lite_mobile_mask
dir: "modules/image/face_detection/pyramidbox_lite_server"
exclude:
  - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/hub_dev/pyramidbox_lite_server_face_detection.tar.gz
    dest: .
    uncompress: True
