name: rbtl3
dir: "modules/text/semantic_model/rbtl3"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/rbtl3/assets.tar.gz
    dest: assets
    uncompress: True
