name: resnet50_vd_dishes
dir: "modules/image/classification/resnet50_vd_dishes"
exclude:
  - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/cv/resnet50_vd_dishes.tar.gz
    dest: model
    uncompress: True
