name: resnet34_v2_imagenet
dir: "modules/image/classification/resnet34_v2_imagenet"
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/cv/resnet34_v2_model.tar.gz
    dest: resnet34_v2_model
    uncompress: True
