name: senta_bow
dir: "modules/text/sentiment_analysis/senta_bow"
exclude:
  - README.md
  - test.py
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/senta_bow_infer_model.tar.gz
    dest: .
    uncompress: True
