name: stylepro_artistic
dir: "modules/image/style_transfer/stylepro_artistic/"
exclude:
    - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/style_transfer/style_projection_enc.tar
    dest: .
    uncompress: True
  -
    url: https://bj.bcebos.com/paddlehub/style_transfer/style_projection_dec.tar
    dest: .
    uncompress: True
